apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: techieglobus
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: appv1:v1
        name: nodejs
