apiVersion: v1
kind: ReplicationController
metadata:
  name: mysoft-v1
spec:
  replicas: 3
  template:
    metadata:
      name: soft
      labels:
        env: beta
    spec:
      containers:
      - image: software:v1
        name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: LoadBalancer
  selector:
    env: beta
  ports:
  - port: 80
    targetPort: 8080
