apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
 
spec:
 rules:
 - host: hello-world.info
   http:
     paths:
     - path: /(.+)
       backend:
         serviceName: web
         servicePort: 8080
