apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
 rules:
 - host: amazon1.com
   http:
     paths:
     - path: /
       backend:
         serviceName: web
         servicePort: 80
