apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: TechieGlobus
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev1
  template:
    metadata:
      labels:
        env: dev1
    spec:
      containers:
      - name: http
        image: httpd
      port:
      - containerPort: 80
      volumeMounts:
      - name:
        mountPath: /usr/local/apache2/htdocs/
  volumes:
  - name: apache1
    nfs:
      server: 192.168.26.130
      path: /opt/test
