apiVersion: v1
kind: Pod
metadata:
  name: samridh5-test
  labels:
    env: test
spec:
  containers:
  - image: samridhrakesh/for:v1
    name: samridhk
    env:
    - name: INTERVAL
      valueFrom:
       configMapKeyRef:
        name: myconfig
        key: INTERVAL
    ports:
    - containerPort: 80
      protocol: TCP
