apiVersion: v1
kind: ReplicationController
metadata:
  name: testrc1
spec:
  replicas: 2
  selector:
    env: beta
    env: pod
  template:
    metadata:
      labels:
        env: pod
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 8080
