apiVersion: v1
kind: ReplicationController
metadata:
  name: testrc
spec:
  replicas: 2
  selector:
    env: beta
  template:
    metadata:
      labels:
        env: beta
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 8080
