apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: rsexp
spec:
  replicas: 2
  selector:
   matchExpressions:
     - key: env
  template:
    metadata:
      labels:
        env: beta
    spec:
      containers:
      - name: pod-rc
        image: httpd
