apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: rs
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
      env: beta
  template:
    metadata:
      labels:
        env: prod
        env: beta
    spec:
      containers:
      - name: pod-rc
        image: httpd
