apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: rs
spec:
  replicas: 2
  selector:
    matchLabels:
      env: pod
  template:
    metadata:
      labels:
        env: pod
    spec:
      containers:
      - name: pod-rc
        image: httpd
