apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
  selector:
    env: beta
---
apiVersion: apps/v1beta1
kind: Statefulset
metadata:
  name: techieglobus
spec:
  serviceName: frontend-service
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        env: beta
    spec:
      containers:
      - image: httpd
        name: mycontainer
        vlumeMounts:
         - name: data
           mountPath: /usr/local/apache2/htdocs
       ports:
       - containerPort: 80
      volumeClaimTemplates:
      - metadata:
        name: data
      spec:
       resources:
        requests:
         storage: 1Gi
       accessModes:
       - ReadWriteOnce
       
